export const HOTEL_SERVICES = [
  { iconClass: "bi bi-wifi", label: "Wifi", id: "wifi" },
  { iconClass: "bi bi-egg-fried", label: "Desayuno", id: "breakfast" },
  { iconClass: "bi bi-briefcase", label: "Dejar equipaje", id: "luggage" },
  { iconClass: "bi bi-water", label: "Piscina", id: "pool" },
  { iconClass: "bi bi-box2-heart", label: "Comida Buffet", id: "buffet" },
  { iconClass: "bi bi-box", label: "Almuerzo", id: "lunch" },
  { iconClass: "bi bi-box", label: "Cena", id: "dinner" },
  { iconClass: "bi bi-tv", label: "TV", id: "tv" },
  { iconClass: "bi bi-snow", label: "Aire acondicionado", id: "air-conditioning" },
  { iconClass: "bi bi-telephone", label: "Teléfono en la habitación", id: "phone" },
  { iconClass: "bi bi-person-up", label: "Servicio a la habitaciones", id: "room-service" },
  { iconClass: "bi bi-heart-pulse", label: "Gimnasio", id: "gym" },
  { iconClass: "bi bi-shield-lock", label: "Caja de seguridad", id: "safe-box" },
  { iconClass: "bi bi-cone-striped", label: "Estacionamiento", id: "parking" },
  { iconClass: "bi bi-sun", label: "Spa", id: "spa" },
  { iconClass: "bi bi-car-front", label: "Servicio de transporte", id: "shuttle-service" },
  { iconClass: "bi bi-people", label: "Salón de reuniones", id: "meeting-room" },
  { iconClass: "bi bi-flower2", label: "Jardín", id: "garden" },
  { iconClass: "bi bi-palette", label: "Actividades recreativas", id: "recreational-activities" },
  { iconClass: "bi bi-bandaid", label: "Atención médica", id: "medical-assistance" },
  { iconClass: "bi bi-headset", label: "Recepción 24 horas", id: "24h-reception" },
  { iconClass: "bi bi-binoculars", label: "Terraza con vistas", id: "rooftop-terrace" },
  { iconClass: "bi bi-controller", label: "Zona de juegos", id: "game-zone" },
  { iconClass: "bi bi-thermometer-sun", label: "Sauna", id: "sauna" },
  { iconClass: "bi bi-cup-hot", label: "Cafetería", id: "coffee-shop" }
];
